spring:
  application:
    name: stayRent
  data:
    mongodb:
      uri: mongodb://localhost:27017/room
#      host: localhost
#      port: 27017
#      username: root
#      password: 123456
#      authentication-database: admin

server:
  port: 8081

logging:
  level:
    root: INFO
    com.system.stayRent: DEBUG

room:
  seed:
    enabled: true


